### ISSUE TITLE
TypeScript sample, including worker

### ISSUE THREAD

**Issue by dtemes** [smrchy/rsmq#104]
Since having typescript definitions is one of the highlighted features i would love to see a typescript example, including a worker. It seems that the rsmq-worker does not have typescript definitions. What would be the best way to process messages from a queue as fast as possible without using polling?

**Comment by smrchy** [comment]
Sorry, did not have time for TS examples yet.
To process mails as quick as possible please have a look at the tests. Your limit is the speed of your Redis server. If the redis server is on a very fast machine that's the speed you can receive messages. I think 5000+ / second should be possible.
