### ISSUE TITLE
Port to Rust using Async

### ISSUE THREAD

**Issue by DavidBM** [smrchy/rsmq#107]
Hey! 

First of all, thanks for this library. It is a nice & simple way to start with queues without too much complexity. 

We are making an async port to rust as we may use it soon. Just though about saying it here in case it is useful to anyone. 

https://github.com/Couragium/rsmq_async

Best!

**Comment by GopherJ** [comment]
Cool!

Also there is https://github.com/dvdplm/rsmq-rust which is not async.

I'm looking forward to use it.

**Comment by DavidBM** [comment]
Yeah. I found that one, but it looked not maintained and was sync. But that is good, depending on if you are using async or not, you have both crates. 

To be honest, migrating the js code to proper rust was very easy when using async.

**Comment by smrchy** [comment]
Thank you @DavidBM 

I added your port to the README. 

Thank you for your work.
