### ISSUE TITLE
option not to update message score

### ISSUE THREAD

**Issue by tigran-gruv** [smrchy/rsmq#108]
After receiveMessage() call message score gets updated and the order in queue is changed. So, next time receiveMessage() returns another message. This behavior is not the exact FIFO logic.
It would be cool to have an option to disable score updates.

Actually, I'm not sure if Redis provides such possibility or not.

**Comment by smrchy** [comment]
The score update is to prevent multiple deliveries of the same message. Changing this behaviour would mean a lot of changes to the core of RSMQ.

Besides if you need exactly this behaviour then your message consumers must be single threaded as the first message must be cleared before the next can be read. This can be done efficiently with Redis Lists. No need for RSMQ then.
