### ISSUE TITLE
Wildcard Queue Names

### ISSUE THREAD

**Issue by Queuecumber** [smrchy/rsmq#12]
I want to receive message from several queues using the same method, can I subscribe using a wildcard? (The issue is that my application can support many different pipelines each of which has its own queue)

**Comment by exinferis** [comment]
As this implies using the infamous redis ```keys```command ([http://redis.io/commands/keys]()), I think this would have serious impacts im terms of performance.

Any thoughts?

**Comment by mpneuried** [comment]
Hi,
within the `.receiveMessage()` method you have to define the queue like `{qname:"myqueue"}`.
So out of the box it's **not possible** to use something like `{qname:"my*"}`.

But you can solve this quite easy yourself
I made a simple [example gist](https://gist.github.com/mpneuried/e62edbe0c30c02422c24)

**Comment by Queuecumber** [comment]
Actually I implemented as a workaround using a single queue and separating the functionality by having a property in the message itself, in hindsight I think either your solution or mine is a better way of doing this rather than having wildcard queues. Thanks a lot for your help
