### ISSUE TITLE
Realtime implementation differ from documentation

### ISSUE THREAD

**Issue by DavidBM** [smrchy/rsmq#128]
In the documentation it mentions that the event will be publish to ` {rsmq.ns}:rt:{qname}` but in the code we can see ` {rsmq.ns}rt:{qname}` instead as you can see here: https://github.com/smrchy/rsmq/blob/f41b7e4eceaec51ea91933f30c54db44e94c07af/index.js#L373

What would be the correct implementation? Changing the documentation would mean that everything remains the same, but it may mean that is not what it was intended to be released. Changing the code would be a breaking change until everyone updates the library.

Original discussion on https://github.com/Couragium/rsmq-async-rs/pull/5#issuecomment-703075012

**Comment by rdlowrey** [comment]
Seems like this is accounted for by postfixing the `":"` to `this.redisns` [in `rsmq/index.js` line 519](https://github.com/smrchy/rsmq/blob/master/index.js#L519) ...

```
this.redisns = opts.ns + ":";
```

Am I missing something?

**Comment by DavidBM** [comment]
You are right! It was brought up in my rust implementation, but it seems we just missreaded. Thanks! Closing this.
