### ISSUE TITLE
Feature: Send Redis PUB msg when msg added to queue

### ISSUE THREAD

**Issue by ksabariraj** [smrchy/rsmq#13]
HI,

Thanks for the module.

I have a issue, I sent message and I got the message ID too. But, the receiver not received any message.

Thanks,
Sabari.

**Comment by smrchy** [comment]
Did the receiver call the `receiveMessage` method? 

Once a messages is places in a queue with the default settings the message will be visible to other receivers. They must call `receiveMessage` though to "poll" for messages. RSMQ will take care that a single message will be delivered only to one recipient at a time. If that recipient does not delete the message it will reappear after the invisibility timeout (default is 30s).

So make sure your receivers are polling the same queue and that your message is visible.

**Comment by ksabariraj** [comment]
Hi,

Thanks for you reply. 

I just use the same code in the example. But, the receiveMessage method not fired.

var RedisSMQ = require("rsmq");
rsmq = new RedisSMQ( {ns: "rsmq"} );
rsmq.createQueue({qname:"sample"}, function (err, resp) {
        if (resp===1) {
            console.log("queue created")
        }
});
rsmq.receiveMessage({qname:"sample"}, function (err, resp) {
	 console.log("No messages ..")
    if (resp && resp.id) {
        console.log("Message received.", resp)  
    }
    else {
        console.log("No messages for me...")
    }
});

// Send message 
rsmq.sendMessage({qname:"sample", message:"sample1"}, function (err, resp) {
		if (resp) {
			console.log("Message sent. ID:", resp);
		}
	});

@smrchy : on more doubt, is it possible to auto delete the message once the receiver received the message?

Thanks,
Sabari.

**Comment by smrchy** [comment]
`receiveMessage` will not "fire". You need to call it **after** you sent a message.

Auto deleting a message upon receipt is currently not supported - and it should be used with care. The idea of this queue is that jobs that fail not fail silently but be retried. If you want to auto-delete a message just let the recipient delete a message immediately after reception.

**Comment by mpneuried** [comment]
A working example of your code will look like:

```js
var RedisSMQ = require("rsmq");
rsmq = new RedisSMQ({s: "rsmq"});

// create the queue
rsmq.createQueue({
	qname: "sample"
}, function(err, resp) {
	if (resp === 1) {
		console.log("queue created")
	}
});

// Send message 
rsmq.sendMessage({
	qname: "sample",
	message: "sample1"
}, function(err, resp) {
	if (resp) {
		console.log("Message sent. ID:", resp);
	}
	if (not err) {

		// receive message
		rsmq.receiveMessage({
			qname: "sample"
		}, function(err, resp) {
			if (resp && resp.id) {
				console.log("Message received.", resp)
			} else {
				console.log("No messages for me...")
			}
		});

	}
});
```

If you want to implement a worker we recommend the module [rsmq-worker](https://github.com/mpneuried/rsmq-worker). 
This module is based on rsmq and WILL fire an event "message" you can listen to ;-)

**Comment by ksabariraj** [comment]
@smrchy  and @mpneuried : Thanks for your's time and update :-)

**Comment by mobrien** [comment]
Follow up question:  can you have a callback invoked without polling. i.e.

Can you do:

rsmq.redis.on('message', callback)

I don't want to poll and want to react immediately without any polling delay when a message is queued.

**Comment by smrchy** [comment]
You can't mix a `subscribe` with a connection. Once a connection ist subscribed no other commands are possible. 

I will consider adding a publish option to notify clients of new messages. But for now the only way for you is to poll for example every second.

**Comment by mobrien** [comment]
Thank you for the quick response.

yes, it would be a great addition to be able to listen for incoming events. I'm creating a parallel pub/sub channel and using it purely to notify when the queue has been posted to.

To be able to do this without the extra pub/sub connection would be ideal.

Also, it would be helpful to pass the queue count information on the event.

**Comment by mobrien** [comment]
Issue should not probably be renamed: "Fire events when queue ready"

**Comment by smrchy** [comment]
### First draft:

We will call the PUBLISH mechanism the `realtime` component. It has to be enabled  when RSQM is initialized via `realtime: true`.

On every new message that is being added to a queue a PUBLISH message will be sent to `{rsmq.ns}:rt:{qname}` with the content `{msgs}`.

So a worker could subscribe to `rsmq:rt*` or more specifically to `rsmq:rt:somequeue`.
Once such a message is received the worked can call `receiveMessage` to receive the message.

**Note**: If you are using multiple workers to "listen" to new messages this way make sure you are not firing a `receiveMessage` on every client to reduce load on the Redis server.

**Comment by smrchy** [comment]
0.9.1 is now published with the Realtime option:

https://github.com/smrchy/rsmq#realtime

**Comment by mobrien** [comment]
Fantastic, I'll check it out. That was quick!.
