### ISSUE TITLE
totalrecv number not as expected

### ISSUE THREAD

**Issue by whyvez** [smrchy/rsmq#137]
Just switched to rsmq from GCP PubSub and loving it! 

I noticed that the `totalrecv` number is not as I expected. Is this count only the number of messages received from the queue from i.e. a subscriber? 

If the `totalrecv` number is higher than `totalsent - msgs` what does that indicate, does it mean some messages were received more than once?

**Comment by smrchy** [comment]
Sorry for the late reply. Yes, totalrecv can be higher when some messages are received multiple times. In the perfert world where all messages are received exactly once those 2 metrics should be the same.
