### ISSUE TITLE
How does "delay" work?

### ISSUE THREAD

**Issue by fiatjaf** [smrchy/rsmq#14]
I looked at the code, but couldn't understand. Redis does not have this "delay before add" feature out-of-the-box, does it? How do you do it?

**Comment by smrchy** [comment]
A delayed message is stored with a timestamp in the future. When you receive a message only messages in the with a timestamp up to the present time will be received.

**Comment by fiatjaf** [comment]
So if you never receive another message after the delayed one you will also never get the delayed message?

**Comment by smrchy** [comment]
RSMQ does not deliver messages. You need to poll for messages with one or more recipients with the `receiveMessage` method.

Let's say you are converting large HD video files into 8 smaller resolutions and formats. So for each HD video you would create 8 messages with "convert" jobs. Now 1000 HD videos will result in 8000 jobs. 
If one of those 8 formats is a hires format that takes a very long time you may want to delay that one format up to 12 hours and make sure that the other formats are handled first. That's what the `delay` is for. 

You could run dozens or hundreds of worker instances that pull their jobs from the queue and convert the videos. The hires format for each video will at best be received in 12 hours.
