### ISSUE TITLE
Just to make it clear

### ISSUE THREAD

**Issue by alexbeletsky** [smrchy/rsmq#16]
This library looks really interesting, but I wonder why native `pub/sub` functions of Redis is not used, instead library is utilizes own implementation.

Was it created before `pub/sub` appeared in Redis?

**Comment by mpneuried** [comment]
**rsmq** is different to `pub/sub`.

|**rsmq**|`pub/sub`|
|:--:|:--:|
|Messages will be delivered to only **one** connected recipient|Messgaes will be shouted out to **all** connected recipients|
|Message will reappear after their invisibility timeout `vt` *(e.g. on processing error)*.|Once published it's gone|
|It's possible to delay a message up to ~115 days|-|
|Messages can be deleted by id|-|
|Messages has to be actively pulled out of the queue|every recipient gets a push and have to be connected all the time|

**Comment by alexbeletsky** [comment]
Great, it's much clearer now. I've built few simple applications yesterday, based on `rsmq` and quite liked the simplicity. I was a little confused by looking inside and haven't seen any Redis `pub/sub` calls, instead some custom implementation, so that's why the issue appeared.

What I'd like also to ask, how `rsmq` decides which worker receives a task if there are concurrent workers running? In my experiments, I can see it's a kind of `round-robin`, isn't it?

**Comment by mpneuried** [comment]
The workers/clients are just pulling the rsmq-queue.
So there is no `round-robin` or other rules inside rsmq. It's just first-come-first-serve.

A typical use of rsmq is using it as task-queue with some workers.
If this matches your requirement, you could have a look at [rsmq-worker](https://github.com/mpneuried/rsmq-worker). It wraps rsmq and simplifies it for this typical usecase. So you just have the process the message events or send messages.

**Comment by alexbeletsky** [comment]
Yes, I already take a look on `worker`. It's exactly what I need.

Thanks,

**Comment by Seamus-melco** [comment]
@alexbeletsky I want to ask, regarding rsmq, is it possible for the receiver to send out an acknowledgement that the message has been consumed?

**Comment by smrchy** [comment]
The receiver **must** send that acknowledgement by deleting the message. Otherwise the message will stay in the queue and appear again after the `vt` timer runs out.
Please check the `createQueue` docs here:

https://github.com/smrchy/rsmq#createqueue

Once your receiver processes and deletes a message it will be removed from the queue.
