### ISSUE TITLE
Ioredis driver

### ISSUE THREAD

**Issue by RK-** [smrchy/rsmq#17]
Hi,
Is it possible to use Ioredis instead of Hiredis as a Redis driver?
With the current driver we can't do high availability.

**Comment by mpneuried** [comment]
Hi,
the `hiredis` module is just an [optional dependency](https://github.com/smrchy/rsmq/blob/master/package.json#L17).
You should be able to prevent the installation of `hiredis` by using the flag `--no-optional`.

E.g:
```
npm install --no-optional
```

See the [npm docs](https://docs.npmjs.com/cli/install).

Please let me know if this is a solution for you?
