### ISSUE TITLE
Can I send message directly by redis client on rails app?

### ISSUE THREAD

**Issue by jerryc-nguyen** [smrchy/rsmq#18]
Hi, 
First of all, many thanks for your great message queue implement using redis. Before known your lib, I try to use rabbitmq to setup message queue system for my app. But it's seem to be overkill and hard to maintain. Now I see your lib, It's seem to be very easy to use and redis server already running in my app. It's really cool.
So I wonder there is a way to use redis client on my rails app to push messages to my nodejs app directly?. I see you have made the rest-rsmq to easy communication between these apps. But I see it will hurt the performance when app have numerous concurrent request.
Looking forward to hearing from you, many thanks.

**Comment by mpneuried** [comment]
Hi,
until you already using redis it should be possible push messaged directly into the rsmq data structures.
Details can be found here: https://github.com/smrchy/rsmq/blob/master/_docs/redis_data_structure.md

The redis multi call writing the message can be found here: https://github.com/smrchy/rsmq/blob/master/index.coffee#L425

I would recommend to create a rsmq ruby module (i guess it's called ruby Gem) and publish it so other people can use it ;-)

**Comment by mpneuried** [comment]
@smrchy are the docs up to date?
also see #19

**Comment by jerryc-nguyen** [comment]
Sorry for a long time to reply. Currently, I use redis pub-sub to communicate between these apps. It works as my expected for now. So I close this issue. Many thanks.
