### ISSUE TITLE
Failed messages should be able to be routed to another queue or list

### ISSUE THREAD

**Issue by timelessvirtues** [smrchy/rsmq#20]
In various flavors of AMQP it is possible to specify a special queue to route messages into after a max number of retry attempts has been exceeded or if the message is undeliverable after a timeout expiration.  Something similar for RSMQ could be valuable to have for debugging.

I know I could implement something similar myself using the "exceeded" event on a worker but what if no workers are online?  Also it isn't clear whether that exceeded count is shared between workers or specific to only that instance.

**Comment by mpneuried** [comment]
The "exceeded" event is just an implementation of [`rsmq-worker`]().
It just checks the `rc` count received by `.receiveMessage()` against a defined value *(`rsmq-worker` > `options.maxReceiveCount`)*.

So your implementation could look like:

```js
// init rsmq-worker
var RSMQWorker = require( "rsmq-worker" );
var worker = new RSMQWorker( "myqueue", {
  maxReceiveCount: 2
});

// grab the internal rsmq instance
var rsmq = worker._getRsmq();

// listen to the exceeded event
worker.on('exceeded', function( msg ){
  // write the exceeded message to
  // NOTE: make sure this queue exists
  rsmq.sendMessage( "YOUR_EXCEEDED_QUEUE", msq, function( err, resp ){
    // handle answer or possible exceptions
  });
});

worker.on( "message", function( message, next, id ){
  // your processing
  next();
});
```

I added this handling also to the [advanced example of rsmq-worker](https://github.com/mpneuried/rsmq-worker#advanced-example).

But a configuration to write exceeded messages automatically to a seperate queue could be a new feature of [`rsmq-worker`](https://github.com/mpneuried/rsmq-worker#todosideas).

**Comment by timelessvirtues** [comment]
Solid addition to the docs.  Just to be completely explicit that `rc` variable is in fact shared between workers, correct?  So if I make 2 attempts to worker A and a single attempt with worker B the `rc` should be 3.

**Comment by mpneuried** [comment]
The `rc` is just the receive count.
It's incremented atomic on every receive. so if no workers are online no one receives messages from rsmq and there will be no `exceeded`.

The exceeded is only handled within the worker as a result of something like:
```js
if( msg.rc > 13 ){ /*...*/ }
```

With `rsmq-worker` you can define a `options.customExceedCheck` to handle the exceed for every message type differently.
This is also shown in the [advanced example](https://github.com/mpneuried/rsmq-worker#advanced-example).
But, again, this is only handled within the worker.
RSMQ itself will not move messages between queues.
That would be technical possible, but we decided to keep rsmq as a core module as simple as possible.

I hope this will clear your questions ;-)

**Comment by timelessvirtues** [comment]
I appreciate the clarification.
