### ISSUE TITLE
Multiple producers supported as well?

### ISSUE THREAD

**Issue by timelessvirtues** [smrchy/rsmq#21]
Just getting my feet wet with your lovely library.  Perhaps I have a fundamental misunderstanding but is it possible to have more than one instance of RSMQ populating the same queues?

**Comment by mpneuried** [comment]
This is possible!
We are using up to 50 EC2 Instances pushing more than 3 million messages per day into a single queue.

In our case only one instance is responsible to reading and processing the message via [`rsmq-worker`](https://github.com/mpneuried/rsmq-worker). But it's also possible to use multiple workers.

**Comment by timelessvirtues** [comment]
Excellent!  It's very possible I glossed over a mention of this in the documentation but I think this capability should be touted more prominently on the site and or documentation.  I can now replace my multiple-producer, multiple-worker RabbitMQ architecture with RSMQ.  :+1:

**Comment by ehynds** [comment]
@mpneuried do you need to protect against multiple producers queueing the same message? Curious how that could be implemented with rmsq (node-resque has queue locking for example).

**Comment by smrchy** [comment]
If multiple producers create the same message *n*-times it will be *n*-times in the queue and will be delivered *n*-times as well. Your consumers that receive this message must take actions that are **idempotent**.

There is no de-duping of same messages.
