### ISSUE TITLE
Delete message on receive

### ISSUE THREAD

**Issue by fiznool** [smrchy/rsmq#22]
Thanks for a great queue library!

For my application, I'm looking to delete a message as it is received. I can currently do this by issuing a `deleteMessage` straight after a `receiveMessage`, but I'd like to go one step further and add support for this in the `receiveMessage` lua script, so that the delete happens atomically.

I was wondering whether you'd accept a PR which implements this functionality.

Here's what I'm thinking:

- Allow a `vt` of `-1` - this indicates that a message should be deleted when it is pulled off the queue.
- Check if `vt` is `-1` in the lua script - if so, run the `zrem` and `hdel` operations to delete the message.

If reusing the `vt` variable isn't desirable, perhaps a new option could be used instead, for example `remove_on_receive`.

**Comment by smrchy** [comment]
This is a good enhancement. I will implement it hopefully this week.

**Comment by smrchy** [comment]
I added a 'popMessage' method. 

Docs: https://github.com/smrchy/rsmq#popmessage

Hope this does what you need.

**Comment by fiznool** [comment]
Marvellous. I'll test this out right away. Thanks for the speedy implementation!

**Comment by smrchy** [comment]
Please close this issue if it works for you.

**Comment by fiznool** [comment]
Works great, thanks!

**Comment by markotom** [comment]
You know if is a good approach to set a TTL to each message?

**Comment by smrchy** [comment]
If you need a TTL (only valid till `some_timestamp`) then you should probably add this from within your application. Just add a `ttl` to your message payload. If the `ttl` is reached just delete the message and don't work on it. 

A TTL feature for RSMQ is not planned as this would make regular housekeeping necessary which is something i'd like to avoid.
