### ISSUE TITLE
update message by id

### ISSUE THREAD

**Issue by fedoral** [smrchy/rsmq#24]
Thanks for this rsmq!

For my application, I send message with delay some seconds. Before it triggered in the future, I may change the message content or the delay time. Can you add this feature? Many thanks.

**Comment by smrchy** [comment]
Manipulation of messages in the queue is not planned.

However it is easy to do for you. Just delete the old message and insert a new one.

The `sendMessage` message answers with the message id which you would have to "remember" in your application either way.

Just use this id with the `deleteMessage` method. If you get a `1` as an answer the message was removed, if you get a `0` it was not found so it must have been received and deleted already.

Then insert your new/updated message.
