### ISSUE TITLE
Event-driven receiving

### ISSUE THREAD

**Issue by mrose17** [smrchy/rsmq#26]
what's your thinking on adding an event for when a queue gets a new message? thanks!

**Comment by mpneuried** [comment]
you can use [rsmq-worker](http://smrchy.github.io/rsmq/rsmq-worker/).
It wraps rsmq and makes it simple to implement a worker around it.
See the [`message` event](https://github.com/mpneuried/rsmq-worker#message).

**Comment by mrose17** [comment]
many thanks! sorry i missed that. thanks for the great packages!
