### ISSUE TITLE
Redis client prefix issue

### ISSUE THREAD

**Issue by ReedD** [smrchy/rsmq#27]
If you set a `prefix` value on the redis client everything starts to break. If you change [line 15](https://github.com/smrchy/rsmq/blob/master/test/test.js#L15) of the unit test file from this:
```
redis = RedisInst.createClient();
````
to this:
```
redis = RedisInst.createClient(6379, '127.0.0.1', {prefix: 'someprefix'});
````
Unit tests will begin to fail.

**Comment by mpneuried** [comment]
hint @smrchy:
Since node_redis v.2.4.0 - 25 Nov, 2015 there's an option `prefix`.

**Comment by smrchy** [comment]
As RSMQ is making heavy use of LUA scripting inside Redis the new `prefix` option of the node Redis client can not be used currently.

**Comment by ReedD** [comment]
So by closing this issue are you saying your intention is never to support it?

**Comment by smrchy** [comment]
By closing this issue i am saying that the Redis client does not work well with the "prefix" option, just as it won't work well with the `keys` command. Working around that is possible but not something that is anywhere a top priority - just pass the prefix via the rsmq `ns` parameter and it works fine.

If you really need this functionality i gladly accept your pull request.
