### ISSUE TITLE
How does a process know that there are messages waiting?

### ISSUE THREAD

**Issue by kpturner** [smrchy/rsmq#29]
Let's say you have a client and server situation.   The client can enqueue messages and the server can pull the messages off the queue.   Can you define the server so that it will "wait" for a message to arrive so that it can then retrieve it and then go back and wait for more?

The documentation seems to imply that you should only retrieve a message if you know one is there,  because a retrieve will return nothing if there are no messages, rather than wait for something to arrive - but that doesn't make much sense :(

There seems to be a missing "consume" method which would allow a process to wait for messages to arrive, and retrieve them when they do.

**Comment by kpturner** [comment]
Is the answer to use rsmq-worker?

**Comment by smrchy** [comment]
Correct. rsmq-worker is a helper that polls a queue for you in defined intervals. 

Depending on your use case you could have a few hundred clients that do just this or just a single one.

**Comment by kpturner** [comment]
OK - so in the scenario where there is a single client and a few hundred workers (any of which might process the message), how would one know when it is safe to dispose of the queue?   Presumably if the client disposes of the queue while workers are waiting for messages on the queue nasty things will happen?

**Comment by smrchy** [comment]
This is the main guarantee of rsmq:

> Guaranteed **delivery of a message to exactly one recipient** within a messages visibility timeout.

So no nasty things will happen, as long as the visibility timeout of a message is long enough for a worker to possibly finish a message.

Let's say you have 1,000,000 video encoding jobs to work on.

* Each video is between 1 and 10 minutes long so lets say each encoding will take max. 10 Minutes. 
* Once an encoding is finished your worker deletes that message.
* Your visibility timeout should be 10 minutes or a little bit more.
* Now every worker will receive a message that will not be received by another worker for at least those 10 minutes.
If a worker does not finish in 10 minutes and deletes the message. The message will show up again.

**Comment by kpturner** [comment]
Yes I think I understand that bit but I didn't explain myself well.   I need to be able to safely delete a queue completely using `deleteQueue()` but I only want to do so when I am sure there are no workers attempting to consume messages from the queue - and my workers will be popping messages rather than receiving them. In my use case as soon as a worker gets a message I don't want any others to have any chance of getting it even if the worker crashes.

**Comment by smrchy** [comment]
Use the `popMessage` for that. And before you remove a queue use `getQueueAttributes` to make sure no messages are "in flight".

**Comment by kpturner** [comment]
Yes still not quite what I need though unfortunately.  It will be quite legitimate for a queue to be empty for long periods of time.   What I need to be able to do is ensure that a client can delete a queue when there are no workers attempting to consume messages from it.  So the trigger will be that all the workers have gone away, not that the queue is empty.

**Comment by kpturner** [comment]
As an aside, there doesn't seem to be a way to tell rsmq-worker to pop messages rather than receive them - so I guess I will just have to delete them on the "message" event.

My worry over deleting queues might not be such a big deal.   My only concern is that I leave queues in redis that are completely redundant and therefore bloat the database.  I don't suppose there is a ttl option on queues?    That aside, I guess I might just be able to delete all the queues on startup using `listQueues` ?

**Comment by smrchy** [comment]
So what you need is a `deleteQueueOnlyWhenEmpty` right?

**Comment by kpturner** [comment]
No not when it is empty - when there are no workers waiting for messages on the queue.  It could be that the queue is empty for hours, but I don't want to delete it because workers are still there waiting. 

Consider this:

A single clients creates a queue.
It then spawns 100 child processes, and each child process becomes a rsmq-worker consuming messages on that queue.
Each worker may process 0-n messages.
If the queue is empty, the workers still wait for messages.
A worker may decide to `stop()` listening for messages (reason not important this this).
When, and only when, all the workers have stopped listening for messages. the client will delete the queue (regardless of whether or not it contains messages).

So this would be like a `deleteQueueWhenNothingListening` type of thing.

**Comment by kpturner** [comment]
Alternatively have a TTL on the queue so that it disappears by itself when nothing is consuming it or enqueueing messages.

What I basically would like is a similar facility to that provided by busmq.  So processings can `attach` to a queue and `detach` from a queue.  When there are no processes attached to a queue, it will expire in redis (after a TTL interval).

**Comment by kpturner** [comment]
I can probably work around this for now, but I have a bigger issue with `rsmq-worker`

https://github.com/mpneuried/rsmq-worker/issues/15
