### ISSUE TITLE
Queue name length and maximum message size

### ISSUE THREAD

**Issue by kpturner** [smrchy/rsmq#30]
The queue name length limitation of 80 characters is a big issue for me.  I create queues that are based on the value of a JWT token and so these exceed the 80 character limitation.  Can this be overridden or just be made bigger?

Also the maximum message size of 65536 can be too small in some cases.  Can the maximum be overridden or increased?

**Comment by smrchy** [comment]
I got the feeling that this tool is either not what you are looking for or you are using it in a wrong way. 

I doubt a longer queue name will solve the structural problems you are facing. If you are creating a queue for each JWT token you will end up with hundreds of queues. It's possible to do that, sure. But that's no something i ever thought about when creating rsmq. The performance and optimization it gains from using a central Redis instance is on the message layer.

The same goes for message length. Keeping messages with 64k+ length in Redis will only work for small workloads unless you are investing in a lot of RAM. Why not store those bigger chunks in S3 and only keep a reference to it?

Have you checked out

https://github.com/smrchy/redis-sessions 

This will let you create a "session" for each of those tokens. Maybe that's closer to what you need.

**Comment by kpturner** [comment]
Actually I already use redis-sessions and have conversed with you on the subject :)

In this instance (where the queue may be named after a JWT) the queue is extremely low volume. It is basically a way for a process to enqueue session based events to be fed back to a client on a websocket. I guess you will just have to trust be that it does fit my use case without a long-winded explanation as to why. The message size limit I can get around - but the queue name length I cannot. I forked the project and made an amendment and hopefully you will accept the pull request.

I am using busmq at the moment and it works well, but I need a lighter alternative also. The biggest fly in the ointment is th fairly serious memory leak in rsmq-worker which I have also forked and fixed.

**Comment by smrchy** [comment]
I just pushed 0.7.1 which includes the 160 queue name increase.

**Comment by kpturner** [comment]
OK thanks - you didn't use the PULL request then?

**Comment by smrchy** [comment]
No, it was missing tests and updated docs. And as it was just one like i quickly added that.
