### ISSUE TITLE
Support throttling or rate limit

### ISSUE THREAD

**Issue by homaily** [smrchy/rsmq#32]
Hello Patrick

What do you think of adding a rate limit (throttling) on received messages in flight?

For example,  Amazon SES has a maximum limit for emails sent per seconds. A typical worker could over send if the queue messages are over the limit. The same applies when you call an API and don't want to overflow it.
 ##
In Redis documentation, there is an example of applying rate limit: http://redis.io/commands/INCR#pattern-rate-limiter-1

Cheers

**Comment by smrchy** [comment]
Currently there is no plan to implement a rate-limit in the rsmq core. 

I think a better place would be a module that uses rsmq and implements this.
