### ISSUE TITLE
Broadcast possibilities

### ISSUE THREAD

**Issue by pukhalski** [smrchy/rsmq#33]
Any plans to support the broadcasting of messages?

**Comment by smrchy** [comment]
Problem with broadcasting is the race on who works on a message, once you have multiple workers. If you just need a simple broadcast system try Redis pub/sub. If you need the guarantees of rsmq there is currently nothing planned.

What you could do if your workers need to know when to poll for a new message is to send a `redis publish` with the message id to some channel.

**Comment by pukhalski** [comment]
I ended up with covering this case by subscribing both to rsmq and redis pub/sub, doing broadcasting via pub/sub and only one consumer with rsmq. Thanks.
