### ISSUE TITLE
Whether the future version supports message priority settings?

### ISSUE THREAD

**Issue by dcboy** [smrchy/rsmq#34]
Whether the future version supports message priority settings?

**Comment by smrchy** [comment]
Could you please explain a bit more with what you mean with priority settings?

Currently RSMQ will try to deliver every message depending on when it becomes first available for delivery. Usually immediately. If other messages are waiting in the queue that need to be delivered first any other new message will have to wait. But then again something is with your workers that they can't keep up.

**Comment by dcboy** [comment]
Is that possible make the message have priority for example: HIGHT,MIDDLE,LOW,or some digit number,my workers process performance so less,so some important message must be process first,eg: SMS Send or Email Send,

**Comment by smrchy** [comment]
The design of RSMQ does not allow for an easy change that supports priorities without breaking stuff.

Why don't you use 3 queues for low, medium and high priority messages?
