### ISSUE TITLE
Why is it not started?

### ISSUE THREAD

**Issue by binodpanta** [smrchy/rsmq#38]
I start redis in standalone mode so it's running at 6379 default port

> npm install rsmq --save
> npm -i (to get into console)
>   RedisSMQ = require("rsmq");
>   rsmq = new RedisSMQ( {host: "127.0.0.1", port: 6379, ns: "rsmq"} );  
>  

I don't see anything in redis, no logging about connection

then rsmq.connected returns true, but any attempts to use further gives me errors like this

such as, after using the createQueue like showin the in the examples, I run 

```
> rsmq.listQueues()
undefined
> TypeError: cb is not a function

```

**Comment by mpneuried** [comment]
as your example shows you have to define a callback (i added an [example](https://github.com/smrchy/rsmq#list-queues) code to the readme).

In general RSMQ ist the core module. So you have/can interact manually with the queue.
The regular case for RSMQ is to process queue messages.
If this is your case you could use [rsmq-worker](https://github.com/mpneuried/rsmq-worker).
in this case the minimal code would be:

> npm install rsmq-worker -S
> npm -i
```js
RSMQWorker = require( "rsmq-worker" );
Worker = new RSMQWorker( "your-queue-name" );
worker.on( "message", function( msg, next, id ){ console.log( "message:", msg ) });
worker.start();
worker.send( "a message!" );
```
