### ISSUE TITLE
[feature] why am I forced to use strings?

### ISSUE THREAD

**Issue by overflowz** [smrchy/rsmq#41]
hi, I looked up at rsmq and I liked it a lot! (tried kue and bull but for some reasons, they add too much overhead and got some bugs which is not acceptable for me).

The only thing I'm interested at the moment is that, why not use JSON.stringify/parse (or MessagePack) directly instead of checking typeof message and throwing error? I really want to send objects instead of just strings, but writing it manually by myself ain't a great thing though.

**Comment by smrchy** [comment]
Well, rsmq uses Redis and Redis eats strings and chokes on objects. 

So allowing objects or creating another abstraction (MessagePack etc.) when all rsmq does is send simple messages would be overhead which i don't like. If you need an object inside the message just `JSON.parse` and `JSON.stringify` it. That's 2 lines. It would be a lot more to handle all possible cases for objects in rsmq.

**Comment by overflowz** [comment]
I got it, thanks for the reply!
