### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by eduardolundgren** [smrchy/rsmq#48]
First of all thank you for `rsmq`, it's an amazingly simple message queue solution. Due to it's simplicity it's a good way to share a message queue layer in different technologies.

In our case, Java was sending messages to Node.js in the same infrastructure, therefore we decided to implement (port) this project. It's available here https://github.com/wedeploy/jrsmq. We've tried to keep the api as similar as possible. If you are interested we can support it as the official Java version.

**Comment by smrchy** [comment]
Eduardo, thank you for your work on the Java Version. I added a section for [RSQM in other languages](https://github.com/smrchy/rsmq#rsmq-in-other-languages) in the README.md.

**Comment by dvdplm** [comment]
Hi there,
I wrote a Rust implementation of rsmq (repo: https://github.com/dvdplm/rsmq-rust). It's early days but it's API complete and seem to work fine with the JS original. It has been a lot of fun to work on and I agree with @eduardolundgren that rsmq is a great tool for many things. Thanks!
Let me know if there's any interest in listing rsmq-rust alongside the Java version and if there is anything in particular I should add/change for that to happen.

**Comment by smrchy** [comment]
Updated the URL for the Java Implementation. See #69

**Comment by duttasuraj** [comment]
Do RSMQ supports .Net Client (.Net Core) or is there any .net implementaion of rsmq ?
