### ISSUE TITLE
Sending message back to visibility immediately

### ISSUE THREAD

**Issue by lucaswxp** [smrchy/rsmq#53]
Hey guys.

Is it possible to, instead of waiting the visibility timeout, send the message back to the queue immediately?

Would "changeMessageVisibility" help me in this? After a message is received, can I call "changeMessageVisibility" with vt 0 to push it back?

**Comment by smrchy** [comment]
Yes, `changeMessageVisibility`will do this for you. I will not be pushed up top but reset to 0. Other messages might still be in front if there is a lot of traffic in your queue.

**Comment by lucaswxp** [comment]
Thanks!
