### ISSUE TITLE
Atomically delete a message and send another?

### ISSUE THREAD

**Issue by lucaswxp** [smrchy/rsmq#54]
The title is self-explanatory, I think. I have the following pseudo-code:

```js
rsmq.deleteMessage({qname:"myqueue", id:message.id}, function(err, resp){
    // the program could crash here and the job would never be finished
    rsmq.sendMessage({qname:"otherqueue", message:"finished-my-job"})
})
```

How to deal with these issues? I know this might not be directly related to RSMQ, I first thought "BRPOPLPUSH " from redis could help me somehow, but not sure how exactly.

**Comment by smrchy** [comment]
There currently is no way to do this case atomically. You would either have to come up with something yourself, or change the pattern you are using. Like use a helper queue for these cases.

**Comment by lucaswxp** [comment]
I understand.

Could you elaborate on the "helper queue" pattern? I would appreciate it.

**Comment by smrchy** [comment]
Create a message in a helper queue that you use to finish the above problem and only when it is finished delete the message.

**Comment by lucaswxp** [comment]
Thanks! I thought about that, but there is still a risk of the message being sent twice or more to the queue if it happens to crash. I'll figure it out.
