### ISSUE TITLE
Send a message with a expiration time

### ISSUE THREAD

**Issue by javiercornejo** [smrchy/rsmq#58]
Hi there.
First I wanna thank you for your project, it is very helpful to me.

I have a question, I didn't find the answer in the documentation. Is there a way to send a message with a expiration time, I mean, if there is no client listening for the message after after a period of time the message expires.

I think I can implement some kind of timeout that calls deleteMessage() after a x period of time but I have no control if a message was send to a client before I deleted.

Regards.

**Comment by smrchy** [comment]
RSMQ has no "server"-component. It's just Redis. So having an expiration would mean the client(s) would have to do some cleanup every n minutes. Not exactly good when there are many of them.

If you need something like a limited validity of a message simply do it on the app side. Add an "valid-till" field to your message and once a message with an expired "valid-till" field is received you discard it. Should be simple and easy to implement.
