### ISSUE TITLE
Create queue if it doesn't exist

### ISSUE THREAD

**Issue by adriennn** [smrchy/rsmq#61]
Hello,

Would it make sense to add an option to sendMessage() that allows creation of a queue if the message is sent to a queue that doesn't exist yet? It would  spare the hassle to either have to check the queueList() first and then create the queue if it doesn't exist or to have to `try...catch` createQueue() or sendMessage(). It would be like in mongodb, where a collection is created on the fly if a document is sent to a collection that doesn't exist.

Something along the lines (untested):

```javascript
RedisSMQ.prototype._checkIfQueueExists(options, qname) {
  this._getQueue(qname, function (resp) {
    if (resp[0][0] === null || resp[0][1] === null || resp[0][2] === null) {
      return this._createQueue(qname)
    }  else { 
      // message can be sent
    }
  })
}
```
Of course this heavily delays sending a message, but rsqm would be able to handle dynamic queue creation internally as an option.

thanks

**Comment by smrchy** [comment]
Dynamic Queue creation is currently not planned. It is possible but also brings a lot of problems:

* How to clean up old / orphaned queues.
* How to handle queues with messages that are never received.

As all of this is happening in a possible shared Redis servers RAM it is not a good idea.

**Comment by adriennn** [comment]
Hi @smrchy , 

I'm not sure how the two problems you mention above are any different in a system where you can't create queues dynamically, but maybe I'm missing something. In any case, thanks for suggesting rsmq-worker, I'll check if out.
