### ISSUE TITLE
Question: What is the difference between using Redis Pub/Sub and RSMQ?

### ISSUE THREAD

**Issue by ivanquirino** [smrchy/rsmq#62]
Redis already have a Pub/Sub API, what are the advantages of using a message queue on top of Redis?

**Comment by smrchy** [comment]
RSMQ stores the messages while pub/sub messages are lost when not received or an error occurs.

Have a look at Amazon SQS. RSMQ is pretty similar to SQS and that is not at all just a pub/sub service.

**Comment by ivanquirino** [comment]
@smrchy So it's like Redis' pub/sub acts only as a transport between connected clients, while RSMQ makes sure messages are actually delivered?

**Comment by smrchy** [comment]
Yep, and a whole lot more. Like if a received message is not deleted after - for example 30s - it will be delivered again.
