### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by alexolivier** [smrchy/rsmq#63]
It would be good to update the message payload and delay. 

Example use case is change the copy and time a user would receive a notification based on an external event.

API could be something like

`updateMessage(messageId, payload, delay)` and it would optionally update the `payload` or `delay` based on what is set.

**Comment by smrchy** [comment]
Simply delete and resend the message. Updating a message payload is a very bad id when the messageid stays the same.
Once you change a payload it is a new message.
