### ISSUE TITLE
Can't use URL

### ISSUE THREAD

**Issue by individual11** [smrchy/rsmq#66]
When using just the url inside of the options object, it never connects. (Also, there is no error that there is no connection, which took me a second as well).

```
rsmq = new RedisSMQ( {options:{url:'redis://<user>:<password>@<hostname>:<port>' );
```
But if I parse the url into its parts and pass them in, it connects fine.

**Comment by TheHollidayInn** [comment]
I think you have an extra key, this works for me:
```
rsmq = new RedisSMQ({ url:'redis://<user>:<password>@<hostname>:<port>'  });
```

Although I am having issues with this in heroku inside my express app, but not inside my worker :P

**Comment by haydn** [comment]
Here's a snippet for the workaround:

```js
const { hostname: host, port } = new URL(REDIS_URL);
const rsmq = new RedisSMQ({ host, port });
```
