### ISSUE TITLE
Creating Delayed Queue

### ISSUE THREAD

**Issue by dev0x10** [smrchy/rsmq#7]
I wonder how to create delayed message queue. Please take a look on my test case and the result

```javascript
it('should create send messagee', function (done) {
    rsmq.deleteQueue({'qname': "myqueue"}, function (res) {
      rsmq.createQueue({qname: "myqueue"}, function (err, resp) {
        if (resp === 1 || err.name === 'queueExists') {
          console.log("queue created");
          rsmq.sendMessage({qname: "myqueue", message: "Hello world", "delay": 1}, function (err, resp) {
            if (resp) {
              console.log("message sent");
              console.log("Message sent. ID:" + resp);
              done();
            }
          });
        }
      });
    });
  });

  it('should receive msg', function (done) {
    rsmq.receiveMessage({qname: "myqueue"}, function (err, resp) {
      if (resp.id) {
        console.log("Message received.")
        console.log(resp);
      }
      else {
        console.log(err);
        console.log("No messages for me...");
      }
    });
  });
```

**Result:**
queue created
message sent
Message sent. ID:e2mp1o4p90fNowqfWpNbxNdAj2huPIKN
  .null
No messages for me...

I didn't put done inside receiveMessage function and wait until timeout but the receiveMessage never triggered again.

**Comment by smrchy** [comment]
You are creating a queue with the default settings (vt: 30, delay: 0, maxsize: 65536).

Then your are sending a message "Hello world" with `delay=1`. The `delay=1` means this particular message will only appear after 1 second to recipients. As you are trying to receive the message right afterwards it won't be received. Which is correct.

* Send a message without the "delay" parameter to receive it immediately.
* Try a `receiveMessage` after 1+ seconds to receive the message.

**Comment by smrchy** [comment]
If you want to create a delayed queue where all messages are delayed by `n` seconds you should use the `delay` parameter with the `createQueue` method.

Your queue worker(s) typically poll the queue every second and will receive all messages after the delay has passed
