### ISSUE TITLE
NOAUTH Authentication support

### ISSUE THREAD

**Issue by stanleybz** [smrchy/rsmq#70]
Is it RSMQ not supporting NOAUTH Authentication?
I've checked there are no `.auth` function under Redis connection, I  added 
```
 if opts.no_auth
       @redis.auth opts.no_auth
```
_on line 53_

for temporary solution

**Comment by smrchy** [comment]
Working on it https://github.com/smrchy/rsmq/commit/e52217e6beaa21c5a00b24c585129703d9c91b16
