### ISSUE TITLE
random queueNotFound errors

### ISSUE THREAD

**Issue by gairom** [smrchy/rsmq#72]
Hi,
I'm getting these errors (see below) from time to time although the queue does exist.
It's working prior to this error and continue working after producing these errors for all messages for about 1-2 minutes and then working ok again.

my packages:
"dependencies": {
"rsmq-promise": "^1.0.1",
"rsmq-worker": "^0.5.2",
"pm2": "^2.9.3",
"redis": "^2.8.0",
"winston": "^2.4.0"
}

Any ideas why or how can I debug this?
Thanks.

queueNotFound: Queue not found at RedisSMQ._handleError (/usr/worker/node_modules/rsmq/index.js:502:14) at RedisSMQ._handleError (/usr/worker/node_modules/rsmq/index.js:19:57) at Multi.callback (/usr/worker/node_modules/rsmq/index.js:111:17) at multi_callback (/usr/worker/node_modules/redis/lib/multi.js:89:14) at Command.callback (/usr/worker/node_modules/redis/lib/multi.js:116:9) at normal_reply (/usr/worker/node_modules/redis/index.js:726:21) at RedisClient.return_reply (/usr/worker/node_modules/redis/index.js:824:9) at JavascriptRedisParser.returnReply (/usr/worker/node_modules/redis/index.js:192:18) at JavascriptRedisParser.execute (/usr/worker/node_modules/redis-parser/lib/parser.js:574:12) at Socket. (/usr/worker/node_modules/redis/index.js:274:27) at Socket.emit (events.js:180:13) at Socket.emit (domain.js:421:20) at addChunk (_stream_readable.js:269:12) at readableAddChunk (_stream_readable.js:256:11) at Socket.Readable.push (_stream_readable.js:213:10) at TCP.onread (net.js:581:20)

**Comment by smrchy** [comment]
Can you produce a test script that triggers this error in a reproducable way?

**Comment by smrchy** [comment]
Closing this. Will reopen this issue once there is a reply.
