### ISSUE TITLE
PHP implementation

### ISSUE THREAD

**Issue by michsindelar** [smrchy/rsmq#74]
I really like this project, so I decided to implement it in PHP. It's available [here](https://github.com/michsindelar/PhpRSMQ).

**Comment by smrchy** [comment]
Great! Thank you. I linked to your project from the Readme:

https://github.com/smrchy/rsmq#rsmq-in-other-languages

It would be nice if you could implement the full protocol - feel free to copy my LUA scripts from the JS source.
