### ISSUE TITLE
Method to tell if a queue is empty

### ISSUE THREAD

**Issue by brandonros** [smrchy/rsmq#76]
Or maybe a function to tell how many jobs are currently in a queue?

**Comment by smrchy** [comment]
Use `getQueueAttributes` It will tell you much more than that:

https://github.com/smrchy/rsmq#getqueueattributes

**Comment by brandonros** [comment]
So `isQueueEmpty` would be `getQueueAttributes` and then `queueAttributes.totalrecv === queueAttributes.totalsent`?

**Comment by smrchy** [comment]
No, when `queueAttributes.msgs` and `queueAttributes.hiddenmsgs` are both `0`.
