### ISSUE TITLE
Only process message once

### ISSUE THREAD

**Issue by brandonros** [smrchy/rsmq#77]
Say a message has a unique ID. Would some other external software be required to make sure that if "process only once" is desired to never put the same message on the queue twice, or is there a way to achieve that with this package?

**Comment by smrchy** [comment]
If you put a message into a RSMQ  queue it will be received by exactly one client. That message now stays "hidden" for other clients.
If that client manages to successfully handle that received message and deletes it before the visibility timeout is reached than you achieved exactly what you needed:

Guaranteed delivery of a message to exactly one recipient within a messages visibility timeout.

See the features section of RSMQ:
https://github.com/smrchy/rsmq#features

**Comment by brandonros** [comment]
I guess I am looking to a way to idempotently place messages onto a queue. I understand that only one client will lock and then process the message, but I don't see any guarantee about viewing each message put onto the queue as unique.

**Comment by smrchy** [comment]
That's not possible with RSMQ and there is no message queue (at least to my knowledge) that has this feature.
