### ISSUE TITLE
Direct call support...

### ISSUE THREAD

**Issue by tracker1** [smrchy/rsmq#8]
I apologize for my lack of knowledge surrounding coffeescript, but I often prefer a call syntax for modules that take parameters...

```
var rsmq = require('rsmq')(options);
```

... over invocation of an instance... If this syntax is supported, It would be nice to see it in the documentation, if it isn't it would be a nice addition.

**Comment by fiatjaf** [comment]
You can probably do

```javascript
var rsmq = new require("rsmq")({host: "127.0.0.1", port: 6379, ns: "rsmq"});
```
