### ISSUE TITLE
Offline Queue - configurable

### ISSUE THREAD

**Issue by 250ok-mikeyoung** [smrchy/rsmq#80]
First off, I like this library.  I wish there was a configuration for the offline queue feature to shut it off.  When you call send and redis is down it pushes the message into the offline queue.  The problem I see with that is redis could be down for a while and you have a potential to back up fairly significantly.  It isn't written to disk so if the program would crash those messages would be lost.  In some cases the offline queue maybe very useful but I wish there was a configuration option to just callback with an error so further steps could be taken upstream.

**Comment by rogerweb** [comment]
There is. It's the `enable_offline_queue` of the redis module itself. Check here: https://github.com/NodeRedis/node_redis#options-object-properties

Cheers,

Roger

**Comment by 250ok-mikeyoung** [comment]
Doh! just realized I put this message in the wrong github repo...  Thanks for the response
