### ISSUE TITLE
msgs and hiddenmsgs

### ISSUE THREAD

**Issue by jandersonld** [smrchy/rsmq#82]
Hi, I'm using getQueueAttributes to get the current number of msgs in the queue, but this also returns hiddenmsgs!

How can I get only msgs that is not hidden??

Thanks! This is a great library :)

**Comment by smrchy** [comment]
Total messages - hidden = non hidden

**Comment by jandersonld** [comment]
I do this, but I had asked if has a way like a parameter in method or another method... 
But thanks :)

**Comment by smrchy** [comment]
I will try to implement a "visiblemsgs" in a future version so it's more clear.
