### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by mlasevich** [smrchy/rsmq#83]
As I needed it, I went ahead and threw together a Python implementation (https://github.com/mlasevich/PyRSMQ) based partially on this and partially on Java version.

It is still a very early version, but I think I got much of the core functionality (except for realtime processing) and unit tests are very much lacking. Hopefully should get better soon :-)

**Comment by smrchy** [comment]
This is great @mlasevich ! I will give you some time to fix the early bug and get the build to pass. Once that works i will gladly link your repo from the RSMQ page.

**Comment by smrchy** [comment]
id generation is somewhat important. Best check the way it is done here, so it results in similar IDs when Node and Python are used: https://github.com/smrchy/rsmq/blob/master/index.coffee#L109

**Comment by mlasevich** [comment]
Ok, I did not realize it is sorting by id - I assumed the sort was by the timestamp. 

Updated to use same algorithm as NodeJS/Java versions - result is a 32 char string, with first 10 being timestamp in lowercase base 36 and the last 22 being random base 62 characters.

I am not sure I understood the comment:

    # The first part is the redis time.toString(36) which
    # lets redis order the messages correctly even when they are
    # in the same millisecond. 

If the time is same the order would be random, as the base36 string will be same, no?

**Comment by smrchy** [comment]
As the Redis time is 5 decimal digits of a second and Redis is single threaded i guess it is unlikely to impossible to get the same time. We use the Redis time to make up for time differences when using different clients that often run in containers with drifting time configs.

**Comment by mlasevich** [comment]
Makes perfect sense. I guess I misunderstood the comment. :-)

**Comment by mlasevich** [comment]
As far as I can tell, *PyRSMQ 0.4.1* works fine with exception of realtime option

I started looking at that for sake of completeness, but I run into a few things - one is that it does not seem to be implemented in the Java version at all, and in the JS version, I only found it to be implemented on sending but not on consuming the queue. Am I missing something, or is implementation on consumption is assumed to be handled by the end-user?

Also, As far as I can tell, the implementation for pub/sub key you are using for a queue ***Queue*** in namepsace ***NS*** would be ***NSrt:Queue*** - with messages being ZCARD of the ***NS:Queue*** - is that correct? I am a little concerned that this approach is subject to collision if namespace ends in ***rt*** (for example, if you have a namespace ***cart*** and namespace ***ca*** and each have queue ***Queue*** - the realtime key for topic for ***ca:Queue*** will be ***cart:Queue*** - which would be already in use.)  Would it make sense to move to a suffix style implementation like ***ca:Queue:rt*** 

Thanks

**Comment by mlasevich** [comment]
Ok, ignore the bit about ***NSrt*** - I did not look close enough and missed the part where a ":" is appended to namespace. 

The question about the consumer stands though.

**Comment by smrchy** [comment]
Hi @mlasevich 
the consumer part is explained here:

https://github.com/smrchy/rsmq#how-to-use-the-realtime-option

RSMQ supplies just the basic methods. Whether a consumer uses a subscription to receive messages is up to the implementation and is not handled by RSMQ. You will use RSMQ to receive the message but the decision about what process issues the `receiveMessage` is up to the implementation.
