### ISSUE TITLE
receiveMessage should return something falsey when the queue is empty

### ISSUE THREAD

**Issue by createthis** [smrchy/rsmq#85]
It's a little awkward trying to determine if an object is empty in js. Wouldn't it be better if we could just do this?

```js
let result = await this.rsmq.receiveMessageAsync(this.rsmq_options);
if (!result) {
  // do something because the queue is empty
}
```

**Comment by smrchy** [comment]
just do a 

```
if (!result.id) {
  // do something because the queue is empty
}
```
There are quite a few people working with RSMQ and a protocol change because of this would break too many things.
