### ISSUE TITLE
documentation regarding pros cons vs RPOPLPUSH

### ISSUE THREAD

**Issue by createthis** [smrchy/rsmq#87]
Hello,

I'm trying to figure out how `rsmq` differs from a simple home grown solution using `RPOPLPUSH`. Could you perhaps list the pros and cons of each method?

I think that `RPOPLPUSH` requires garbage collection of the processing queue somehow, whereas this implementation uses timeouts, so it does not require garbage collection.

`RPOPLPUSH` is probably faster though, right?

Thanks.

**Comment by smrchy** [comment]
I was looking into RPOPLPUSH when i started working on this. For working with visibility timeouts it means a lot of moving messages around with some kind of "garbage collecting" / "housekeeping" routine.
I think the implementation in RSMQ that works with sorted sets is more efficient and a lot cleaner.
