### ISSUE TITLE
[Feature request] Exchanges

### ISSUE THREAD

**Issue by aggarwaldev** [smrchy/rsmq#88]
Hey!

I'm impressed with the work on `rsmq`.
I would like to propose a new feature which is already implemented in RabitMQ known as `exchanges`
`Exchanges` provide a reliable way of MQ and may work in three modes: `direct`, `fanout` and `topic`.

See this for more info on `exchanges`: https://stackoverflow.com/a/8276935

I'm working on an application which requires `topic` exchange and since this implementation may take time, in the meantime, can you please suggest me a work-around on the top of redis?

Thank you!

**Comment by smrchy** [comment]
I doubt "topic" can be realized on top of Redis without a lot of helping data structures that need to be maintained and cleaned. Please remember the "S" in RSMQ stands for "simple". RSMQ can do a few things really well if you take a stable and available Redis server for granted. Those things are a lot harder and more expensive to achieve with other systems. Please see the features:

https://github.com/smrchy/rsmq#features

For everything else you should probably look somewhere else.
