### ISSUE TITLE
Promisified method implementation

### ISSUE THREAD

**Issue by tracker1** [smrchy/rsmq#9]
It would be nice if you added a promisified implementation...

```
var rsmq = require('rsmq')(options).promise;

...

rsmq.receiveMessage(...)
  .then(function(message){
    ...
  })
  ...
  .catch(function(err){
  });
```

You could either shim in promises via `i-promise` or use something like `bluebird` directly.

**Comment by naugtur** [comment]
Since you mentioned bluebird, I was able to use rsmq successfully with:
```
rsmq = bluebird.promisifyAll(new require('rsmq')(opts));
rsmq.<anymethod>Async({ qname etc. }).then(...)
```
