### ISSUE TITLE
receiveMessage vt not working

### ISSUE THREAD

**Issue by FractalMind** [smrchy/rsmq#90]
`rsmq.receiveMessageAsync({qname: queueName, vt:(60*3)})`

Doesn't make the message invisible, I have to 

`rsmq.changeMessageVisibilityAsync({qname: queueName, id: resp.id, vt: (60 * 3)})` 
all the time after receiving a message. I'm I missing something?

**Comment by smrchy** [comment]
Hi @FractalMind 
i just tried to reproduce this with this test:

https://github.com/smrchy/rsmq/commit/224f0888c5558c92ce79903f964c8f3bea157332

However it works fine. Could you supply some code to reproduce your issue?
