### ISSUE TITLE
Does `sendMessage` return a number or a string?

### ISSUE THREAD

**Issue by cakoose** [smrchy/rsmq#99]
[index.d.ts:44](https://github.com/smrchy/rsmq/blob/346c6abe4364eaeb869eb3c961143afe4d029ae1/index.d.ts#L44) seems to indicate that `sendMessage` returns a number.

But based on the ReadMe and the code, it looks like it returns a string.

**Comment by smrchy** [comment]
It does indeed return a string. Fixed that. Will be included in the next release.
